services:
  - type: web
    name: rithits-api
    env: docker
    region: ohio
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres.efwugnceepwylwdlzktw:Calaveroli127@aws-1-us-east-2.pooler.supabase.com:6543/postgres?pgbouncer=true"
      - key: DIRECT_URL
        value: "postgresql://postgres.efwugnceepwylwdlzktw:Calaveroli127@aws-1-us-east-2.pooler.supabase.com:5432/postgres"
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "3002"
      - key: FRONTEND_URL
        value: "https://project-nyxdj.vercel.app"
      - key: REDIS_HOST
        value: "localhost"
      - key: REDIS_PORT
        value: "6379"
      - key: ELASTICSEARCH_NODE
        value: "http://localhost:9200"
      - key: MINIO_ENDPOINT
        value: "localhost"
      - key: MINIO_PORT
        value: "9000"
      - key: MINIO_ACCESS_KEY
        value: "admin"
      - key: MINIO_SECRET_KEY
        value: "password123"
    disk:
      name: uploads-disk
      mountPath: /app/uploads
      sizeGB: 10
